### ISSUE TITLE
bwinf

### ISSUE THREAD

**Issue by minad** [felixknispel/BwInf-J1#1]
Hi Felix,

Daniel hier von der Info-AG. Könntest du das Repo bis zum BWINF hier noch verstecken, sodass es nicht für alle sichtbar ist? In Github kannst du dir als Schüler private Repositories beantragen. Alternativ solltest du das Repository erstmal löschen und nach dem BWINF wieder hochladen.

Viele Grüße
Daniel

**Comment by minad** [comment]
Betrifft beide Bwinf-J1 und J2 repos

**Comment by felixknispel** [comment]
Klar, mach ich. Ich hatte es vorher schon private, hatte es bloß heute public gemacht damit ihr heute und morgen drauf zugreifen könnt.
